// flow-typed signature: 40a37b679d02b99c51676d5499499390
// flow-typed version: <<STUB>>/react-test-renderer/shallow_v16.x.x/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-test-renderer/shallow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-test-renderer/shallow' {
  declare module.exports: any;
}
